/**
 * Server functions for querying the read-only runtime conversation DB.
 * All of these run only on the server (better-sqlite3 doesn't run in the browser).
 */
import { createServerFn } from "@tanstack/react-start";
import { existsSync } from "node:fs";
import { z } from "zod";
import { realMessageWhere } from "~/lib/conversation/filters";
import { addMessageScopeFilters, messageScopeInput, messageScopeWhere, type MessageScope } from "~/lib/conversation/scope";
import { bucket, dayBounds, monthBounds } from "~/lib/conversation/time";
import { STOPWORDS } from "~/lib/conversation/stopwords";
import { tokenize } from "~/lib/conversation/tokenize";
import { db, getDataGeneratedAt, projectPath, readTextFile, withDbCache } from "~/lib/server-db";
import { resolveMessageScope } from "~/server/scope";

// ----- English-baseline frequencies (wordfreq, generated by scripts/build-baseline.py) -----
//
// Loaded once at module import. The baseline is a Zipf score per word (log10 per-billion;
// 0 = unknown). We convert to a per-token rate at use-time: pow(10, zipf - 9) gives
// frequency-per-token (since 10^9 tokens ≈ 1 billion). This lets us compute:
//
//   corpus_rate(w) / baseline_rate(w) = "lift" — how much more we use w than average.
//
// Generated by `.venv-baseline/bin/python3 scripts/build-baseline.py`. If the file is
// missing (e.g. fresh checkout), we fall back to an empty map: every lookup returns
// the unknown-word default (zipf=1.0 ≈ "extremely rare in English"), which gives all
// our words a uniformly-large lift and iconic_score collapses to a constant. The UI
// guards against that case but you should regenerate.
type BaselineFile = {
  _meta?: Record<string, unknown>;
  frequencies?: Record<string, number>;
};

const BASELINE_PATH = projectPath("data/baseline-frequencies.json");
const BASELINE: Record<string, number> = (() => {
  try {
    const raw = readTextFile(BASELINE_PATH);
    const parsed = JSON.parse(raw) as BaselineFile;
    const freqs = parsed.frequencies ?? {};
    const meta = parsed._meta ?? {};
    console.log(
      `[baseline] loaded ${Object.keys(freqs).length} words from ${BASELINE_PATH}` +
        (meta.coverage_pct != null ? ` (coverage ${meta.coverage_pct}%)` : ""),
    );
    return freqs;
  } catch (err) {
    console.warn(
      `[baseline] could not load ${BASELINE_PATH}: ${(err as Error).message}. ` +
        `Lift/iconic scoring will be degraded. Run 'scripts/build-baseline.py'.`,
    );
    return {};
  }
})();

// Zipf score for unknown words. 1.0 ≈ ~1 in 10^8 tokens — moderately rare.
// Lower = more lift for unknowns (good for in-jokes/names) but also lifts pure typos.
const UNKNOWN_ZIPF = 1.0;

function zipfToRate(zipf: number): number {
  // Zipf = log10(per-billion). per-token = 10^(zipf - 9).
  return Math.pow(10, zipf - 9);
}

function baselineZipfFor(word: string): number {
  const z = BASELINE[word];
  // Treat 0 (= "not in wordfreq large list") as unknown.
  if (z == null || z === 0) return UNKNOWN_ZIPF;
  return z;
}

// ----- shared types -----

export type Stats = {
  total: number;
  me: number;
  them: number;
  first_ts: number;
  last_ts: number;
  attachments: number;
  tapbacks: number;
  replies: number;
  total_words: number;
  days_with_messages: number;
  longest_gap_days: number;
  longest_gap_start: number;
  longest_gap_end: number;
  busiest_day_ymd: string;
  busiest_day_count: number;
  median_gap_seconds: number;
  reply_med_me_to_them: number;
  reply_med_them_to_me: number;
  total_chars: number;
  generated_at: string;
};

function homeScopeCacheKey(name: string, scope: MessageScope): string {
  return `home:${name}:${JSON.stringify({
    from: scope.from ?? "",
    phase: scope.phase ?? "",
    sender: scope.sender ?? "both",
    to: scope.to ?? "",
  })}`;
}

// ----- stats -----
export const getStats = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }): Promise<Stats> => {
  const resolved = resolveMessageScope(data);
  return withDbCache(homeScopeCacheKey("stats", resolved), () => {
  const d = db();
  const scope = messageScopeWhere(resolved);

  const base = d.prepare(`
    SELECT
      COUNT(*) AS total,
      SUM(is_from_me) AS me,
      SUM(1-is_from_me) AS them,
      MIN(ts) AS first_ts,
      MAX(ts) AS last_ts,
      SUM(has_attachment) AS attachments,
      SUM(CASE WHEN associated_message_type BETWEEN 2000 AND 2005 THEN 1 ELSE 0 END) AS tapbacks,
      SUM(CASE WHEN reply_to_guid IS NOT NULL THEN 1 ELSE 0 END) AS replies,
      SUM(word_count) AS total_words,
      SUM(char_count) AS total_chars
    FROM messages m
    ${scope.sql}
  `).get(...scope.args) as Record<string, number>;

  const dayCounts = new Map<string, number>();
  const dayRows = d.prepare(`SELECT m.ts FROM messages m ${scope.sql}`).iterate(...scope.args) as IterableIterator<{ ts: number }>;
  for (const row of dayRows) {
    const ymd = bucket(row.ts, "ymd");
    dayCounts.set(ymd, (dayCounts.get(ymd) ?? 0) + 1);
  }
  const busy = [...dayCounts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0];

  // longest gap between consecutive messages (real-text only — exclude tapbacks)
  const realScope = messageScopeWhere(resolved, "m", [realMessageWhere("text_turn", "m")]);
  const gap = d.prepare(`
    WITH ordered AS (
      SELECT ts, LAG(ts) OVER (ORDER BY ts) AS prev_ts
      FROM messages m
      ${realScope.sql}
    )
    SELECT prev_ts AS gap_start, ts AS gap_end, (ts - prev_ts) AS gap_sec
    FROM ordered
    WHERE prev_ts IS NOT NULL
    ORDER BY gap_sec DESC
    LIMIT 1
  `).get(...realScope.args) as { gap_start: number; gap_end: number; gap_sec: number } | undefined;

  // median gap
  const medGap = d.prepare(`
    WITH ordered AS (
      SELECT ts, LAG(ts) OVER (ORDER BY ts) AS prev_ts
      FROM messages m
      ${realScope.sql}
    ),
    diffs AS (SELECT (ts - prev_ts) AS gap FROM ordered WHERE prev_ts IS NOT NULL)
    SELECT gap FROM diffs ORDER BY gap LIMIT 1 OFFSET (SELECT COUNT(*)/2 FROM diffs)
  `).get(...realScope.args) as { gap: number } | undefined;

  // median reply latency by direction (real reply = previous msg from other party)
  const medReply = d.prepare(`
    WITH ordered AS (
      SELECT ts, is_from_me,
             LAG(ts) OVER (ORDER BY ts) AS prev_ts,
             LAG(is_from_me) OVER (ORDER BY ts) AS prev_from_me
      FROM messages m
      ${realScope.sql}
    ),
    me_replies AS (
      SELECT (ts - prev_ts) AS lat FROM ordered
      WHERE prev_ts IS NOT NULL AND is_from_me=1 AND prev_from_me=0 AND (ts - prev_ts) < 86400
    ),
    them_replies AS (
      SELECT (ts - prev_ts) AS lat FROM ordered
      WHERE prev_ts IS NOT NULL AND is_from_me=0 AND prev_from_me=1 AND (ts - prev_ts) < 86400
    )
    SELECT
      (SELECT lat FROM me_replies ORDER BY lat LIMIT 1 OFFSET (SELECT COUNT(*)/2 FROM me_replies)) AS me_to_them,
      (SELECT lat FROM them_replies ORDER BY lat LIMIT 1 OFFSET (SELECT COUNT(*)/2 FROM them_replies)) AS them_to_me
  `).get(...realScope.args) as { me_to_them: number; them_to_me: number } | undefined;

  return {
    total: base.total ?? 0,
    me: base.me ?? 0,
    them: base.them ?? 0,
    first_ts: base.first_ts ?? 0,
    last_ts: base.last_ts ?? 0,
    attachments: base.attachments ?? 0,
    tapbacks: base.tapbacks ?? 0,
    replies: base.replies ?? 0,
    total_words: base.total_words ?? 0,
    total_chars: base.total_chars ?? 0,
    days_with_messages: dayCounts.size,
    longest_gap_days: gap ? Math.round(gap.gap_sec / 86400) : 0,
    longest_gap_start: gap?.gap_start ?? 0,
    longest_gap_end: gap?.gap_end ?? 0,
    busiest_day_ymd: busy?.[0] ?? "",
    busiest_day_count: busy?.[1] ?? 0,
    median_gap_seconds: medGap?.gap ?? 0,
    reply_med_me_to_them: medReply?.me_to_them ?? 0,
    reply_med_them_to_me: medReply?.them_to_me ?? 0,
    generated_at: getDataGeneratedAt(),
  };
  });
});

// ----- monthly counts -----
export const getMonthly = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }) => {
    const resolved = resolveMessageScope(data);
    return withDbCache(homeScopeCacheKey("monthly", resolved), () => {
    const scope = messageScopeWhere(resolved);
    const rows = db().prepare(`
      SELECT m.ts, m.is_from_me
      FROM messages m
      ${scope.sql}
      ORDER BY m.ts
    `).all(...scope.args) as Array<{ ts: number; is_from_me: number }>;
    const byMonth = new Map<string, { ym: string; me: number; them: number; total: number }>();
    for (const row of rows) {
      const ym = bucket(row.ts, "ym");
      const month = byMonth.get(ym) ?? { ym, me: 0, them: 0, total: 0 };
      month.total += 1;
      if (row.is_from_me === 1) month.me += 1;
      else month.them += 1;
      byMonth.set(ym, month);
    }
    return [...byMonth.values()].sort((a, b) => a.ym.localeCompare(b.ym));
    });
  });

// ----- hour x weekday heatmap -----
export const getHeatmap = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }) => {
	const resolved = resolveMessageScope(data);
	return withDbCache(homeScopeCacheKey("heatmap", resolved), () => {
	const scope = messageScopeWhere(resolved);
    const counts = new Map<string, { dow: number; hour: number; n: number }>();
    const rows = db().prepare(`
      SELECT m.ts
      FROM messages m
      ${scope.sql}
    `).iterate(...scope.args) as IterableIterator<{ ts: number }>;
    for (const row of rows) {
      const dow = bucket(row.ts, "wday");
      const hour = bucket(row.ts, "hour");
      const key = `${dow}:${hour}`;
      const current = counts.get(key) ?? { dow, hour, n: 0 };
      current.n += 1;
      counts.set(key, current);
    }
    return [...counts.values()].sort((a, b) => a.dow - b.dow || a.hour - b.hour);
  });
	});

// ----- top emojis (rough — counts code-point ranges) -----
const GAME_GRID = new Set([
  "⬛","⬜","🟧","🟨","🟩","🟦","🟪","🟥","🟫",
  "⚫","⚪","🔴","🟠","🟡","🟢","🔵","🟣","🟤",
  "⭐","✅","❌","➡️","⬅️","⬆️","⬇️",
]);
export const getEmojiTop = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }) => {
    const resolved = resolveMessageScope(data);
    return withDbCache(homeScopeCacheKey("emoji-top", resolved), () => {
    const scope = messageScopeWhere(resolved, "m", ["m.text IS NOT NULL", "m.text != ''"]);
    const rows = db().prepare(`
      SELECT m.text FROM messages m ${scope.sql}
    `).iterate(...scope.args) as IterableIterator<{ text: string }>;
    const counts = new Map<string, number>();
    const emoRe = /(?:\p{Extended_Pictographic}(?:‍\p{Extended_Pictographic})*[️]?)/gu;
    for (const r of rows) {
      const m = r.text.match(emoRe);
      if (!m) continue;
      for (const e of m) {
        if (GAME_GRID.has(e)) continue;
        counts.set(e, (counts.get(e) ?? 0) + 1);
      }
    }
    const out = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 30).map(([emoji, n]) => ({ emoji, n }));
    return out;
    });
  });

// ----- search messages -----
const browseFilterSchema = z.enum(["all", "with_attachment", "tapbacks", "replies"]);
type BrowseFilter = z.infer<typeof browseFilterSchema>;

const searchInput = messageScopeInput.extend({
  q: z.string().min(1).max(100),
  limit: z.number().int().min(1).max(200).default(50),
  offset: z.number().int().min(0).max(100_000).default(0),
  filter: browseFilterSchema.default("all"),
});

export const searchMessages = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => searchInput.parse(d))
  .handler(async ({ data }) => {
    // FTS5 query — escape dangerous chars by quoting term
    const safe = `"${data.q.replace(/"/g, '""')}"`;
    const resolved = resolveMessageScope(data);
    const where = ["messages_fts MATCH ?", browseFilterWhere(data.filter)];
    const args: Array<string | number> = [safe];
    addMessageScopeFilters(where, args, resolved);
	    const rows = db().prepare(`
	      SELECT m.id, m.ts, m.date_iso, m.is_from_me, m.has_attachment,
	             m.associated_message_type,
	             sm.segment_id, s.topic_id, sc.category AS segment_category,
	             sc.category_status AS segment_category_status,
	             snippet(messages_fts, 0, '<mark>', '</mark>', '…', 24) AS snippet,
	             m.text
	      FROM messages_fts
	      JOIN messages m ON m.id = messages_fts.rowid
	      LEFT JOIN seg_msg_segment sm ON sm.msg_id = m.id
	      LEFT JOIN seg_segments s ON s.id = sm.segment_id
	      LEFT JOIN seg_segment_categories sc ON sc.segment_id = sm.segment_id
	      WHERE ${where.join(" AND ")}
	      ORDER BY m.ts DESC
	      LIMIT ? OFFSET ?
    `).all(...args, data.limit, data.offset) as Array<{
      id: number;
      ts: number;
      date_iso: string;
      is_from_me: number;
	      has_attachment: number;
	      associated_message_type: number | null;
	      segment_id: number | null;
	      topic_id: number | null;
	      segment_category: string | null;
	      segment_category_status: string | null;
	      snippet: string;
	      text: string;
	    }>;

    const total = db().prepare(`
      SELECT COUNT(*) AS n
      FROM messages_fts
      JOIN messages m ON m.id = messages_fts.rowid
      WHERE ${where.join(" AND ")}
    `).get(...args) as { n: number };

    return { rows, total: total.n };
  });

// ----- list messages by ts page (for browser virtualization) -----
const listInput = messageScopeInput.extend({
  before: z.number().int().nullable().optional(),
  after: z.number().int().nullable().optional(),
  limit: z.number().int().min(1).max(200).default(100),
  filter: browseFilterSchema.default("all"),
});

export const listMessages = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => listInput.parse(d))
  .handler(async ({ data }) => {
    const where: string[] = [];
    const args: any[] = [];
    where.push(browseFilterWhere(data.filter));

    const resolved = resolveMessageScope(data);
    addMessageScopeFilters(where, args, resolved);

    if (data.before != null) {
      where.push("m.ts < ?");
      args.push(data.before);
    }
    if (data.after != null) {
      where.push("m.ts > ?");
      args.push(data.after);
    }

    // After=X → return oldest matches after X, ASC.
    // Otherwise (no after or before set) → return newest available, DESC, then reverse so display is chronological.
    const order = data.after != null ? "ASC" : "DESC";
    const sql = `
	      SELECT m.id, m.ts, m.date_iso, m.ymd, m.is_from_me, m.has_attachment,
	             m.text, m.reply_to_guid, m.associated_message_type, m.balloon_bundle_id,
	             m.rich_link_url,
	             sm.segment_id, s.topic_id, sc.category AS segment_category,
	             sc.category_status AS segment_category_status
	      FROM messages m
	      LEFT JOIN seg_msg_segment sm ON sm.msg_id = m.id
	      LEFT JOIN seg_segments s ON s.id = sm.segment_id
	      LEFT JOIN seg_segment_categories sc ON sc.segment_id = sm.segment_id
	      WHERE ${where.join(" AND ")}
      ORDER BY m.ts ${order}
      LIMIT ?
    `;
    args.push(data.limit);
    let rows = db().prepare(sql).all(...args) as Array<any>;
    if (order === "DESC") rows = rows.reverse();
    return rows.map((row) => ({ ...row, ymd: bucket(row.ts, "ymd") }));
  });

function browseFilterWhere(filter: BrowseFilter): string {
  if (filter === "with_attachment") return "m.has_attachment=1";
  if (filter === "tapbacks") return realMessageWhere("reaction_add", "m");
  if (filter === "replies") return "m.reply_to_guid IS NOT NULL";
  return realMessageWhere("browsable_message", "m");
}

// ----- jump to date -----
export const jumpToDate = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => z.object({ ymd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) }).parse(d))
  .handler(async ({ data }) => {
    const bounds = dayBounds(data.ymd);
    const row = db().prepare(`
      SELECT m.id, m.ts FROM messages m WHERE m.ts >= ?
        AND (m.associated_message_type IS NULL OR m.associated_message_type < 2000)
      ORDER BY m.ts ASC LIMIT 1
    `).get(bounds.start) as { id: number; ts: number } | undefined;
    return row ?? null;
  });

// ----- attachments page -----
const attInput = z.object({
  from: messageScopeInput.shape.from,
  to: messageScopeInput.shape.to,
  sender: messageScopeInput.shape.sender,
  phase: messageScopeInput.shape.phase,
  limit: z.number().int().min(1).max(500).default(120),
  offset: z.number().int().min(0).default(0),
});

type AttachmentSummaryRow = {
  id: number;
  mime_type: string | null;
  total_bytes: number | null;
  is_image: number;
  is_video: number;
  thumb_path: string | null;
  is_from_me: number;
  ts: number;
  category: string | null;
  category_status: string | null;
};

type AttachmentTotal = {
  total: number;
  with_thumb: number;
  images: number;
  videos: number;
  other: number;
  total_bytes: number;
};

export const listAttachments = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => attInput.parse(d))
  .handler(async ({ data }) => {
    const hasAttachmentClusters = Boolean(
      db()
        .prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'seg_attachment_clusters'")
        .get(),
    );
    const clusterSelect = hasAttachmentClusters
      ? `
             c.segment_id, c.cluster_id, c.cluster_label, c.cluster_size,
             c.caption AS cluster_caption, c.similar_attachment_ids, c.embedding_method,
      `
      : `
             NULL AS segment_id, NULL AS cluster_id, NULL AS cluster_label, NULL AS cluster_size,
             NULL AS cluster_caption, NULL AS similar_attachment_ids, NULL AS embedding_method,
      `;
    const clusterJoin = hasAttachmentClusters
      ? "LEFT JOIN seg_attachment_clusters c ON c.attachment_id = a.id"
      : "";
    const resolved = resolveMessageScope(data);
    const listScope = messageScopeWhere(resolved, "m", ["a.is_image = 1", "a.thumb_path IS NOT NULL"]);
    const candidateRows = db().prepare(`
      SELECT a.id, a.message_id, a.thumb_path, a.mime_type, a.total_bytes, a.filename,
             ${clusterSelect}
             m.ts, m.date_iso, m.is_from_me, m.text
      FROM attachments a
      JOIN messages m ON m.id = a.message_id
      ${clusterJoin}
      ${listScope.sql}
      ORDER BY m.ts DESC
    `).all(...listScope.args) as Array<any>;
    const deployableRows = candidateRows.filter((row) =>
      hasDeployableAttachmentThumb(row.thumb_path),
    );
    const rows = deployableRows.slice(data.offset, data.offset + data.limit);

    const similarIds = [
      ...new Set(
        rows.flatMap((row) => parseSimilarIds(row.similar_attachment_ids)),
      ),
    ];
    const similarRows = similarIds.length > 0
      ? db().prepare(`
          SELECT a.id, a.message_id, a.thumb_path, a.total_bytes,
                 m.ts, m.is_from_me, m.text
          FROM attachments a
          JOIN messages m ON m.id = a.message_id
          WHERE a.id IN (${similarIds.map(() => "?").join(",")})
        `).all(...similarIds) as Array<any>
      : [];
    const similarById = new Map(
      similarRows
        .filter((row) => hasDeployableAttachmentThumb(row.thumb_path))
        .map((row) => [row.id, row]),
    );
    const hydratedRows = rows.map((row) => ({
      ...row,
      similar: parseSimilarIds(row.similar_attachment_ids)
        .map((id) => similarById.get(id))
        .filter(Boolean)
        .slice(0, 6),
    }));

    const totalScope = messageScopeWhere(resolved, "m");
    const rawTotal = db().prepare(`
      SELECT
        COUNT(*) AS total,
        COALESCE(SUM(CASE WHEN thumb_path IS NOT NULL THEN 1 ELSE 0 END), 0) AS with_thumb,
        COALESCE(SUM(is_image), 0) AS images,
        COALESCE(SUM(is_video), 0) AS videos,
        COALESCE(SUM(CASE WHEN is_image = 0 AND is_video = 0 THEN 1 ELSE 0 END), 0) AS other,
        COALESCE(SUM(total_bytes), 0) AS total_bytes
      FROM attachments a
      JOIN messages m ON m.id = a.message_id
      ${totalScope.sql}
    `).get(...totalScope.args) as AttachmentTotal;

    const summaryRows = db().prepare(`
      SELECT a.id, a.mime_type, a.total_bytes, a.is_image, a.is_video, a.thumb_path,
             m.is_from_me, m.ts,
             sc.category, sc.category_status
      FROM attachments a
      JOIN messages m ON m.id = a.message_id
      LEFT JOIN seg_msg_segment sm ON sm.msg_id = m.id
      LEFT JOIN seg_segment_categories sc ON sc.segment_id = sm.segment_id
      ${totalScope.sql}
    `).all(...totalScope.args) as AttachmentSummaryRow[];
    const deployableThumbIds = new Set(
      summaryRows
        .filter((row) => hasDeployableAttachmentThumb(row.thumb_path))
        .map((row) => row.id),
    );
    const total: AttachmentTotal = {
      ...rawTotal,
      with_thumb: deployableThumbIds.size,
    };
    const summaryRowsWithDeployableThumbs = summaryRows.map((row) =>
      deployableThumbIds.has(row.id) ? row : { ...row, thumb_path: null },
    );

    const clusters = hasAttachmentClusters
      ? buildDeployableAttachmentClusters(deployableRows)
      : [];

    return {
      rows: hydratedRows,
      total,
      clusters,
      summary: buildAttachmentSummary(summaryRowsWithDeployableThumbs),
    };
  });

const attachmentThumbExistsCache = new Map<string, boolean>();

function hasDeployableAttachmentThumb(thumbPath: string | null): boolean {
  if (!thumbPath) return false;
  const normalized = thumbPath.replace(/^\/+/, "");
  if (!normalized.startsWith("attachments/") || normalized.includes("..")) {
    return false;
  }
  const cached = attachmentThumbExistsCache.get(normalized);
  if (cached != null) return cached;
  const exists = existsSync(projectPath(`public/${normalized}`));
  attachmentThumbExistsCache.set(normalized, exists);
  return exists;
}

function buildDeployableAttachmentClusters(rows: Array<any>) {
  const clusters = new Map<number, {
    cluster_id: number;
    cluster_label: string;
    cluster_size: number;
    embedding_method: string;
  }>();
  for (const row of rows) {
    if (row.cluster_id == null) continue;
    const cluster = clusters.get(row.cluster_id) ?? {
      cluster_id: row.cluster_id,
      cluster_label: row.cluster_label ?? "Unclustered",
      cluster_size: 0,
      embedding_method: row.embedding_method ?? "unknown",
    };
    cluster.cluster_size += 1;
    clusters.set(row.cluster_id, cluster);
  }
  return [...clusters.values()].sort((a, b) =>
    b.cluster_size - a.cluster_size || a.cluster_id - b.cluster_id,
  );
}

function buildAttachmentSummary(rows: AttachmentSummaryRow[]) {
  const categories = new Map<string, { label: string; n: number; with_thumb: number }>();
  const mimes = new Map<string, {
    label: string;
    n: number;
    total_bytes: number;
    me: number;
    them: number;
    with_thumb: number;
    images: number;
    videos: number;
  }>();
  const months = new Map<string, { ym: string; n: number; images: number; videos: number; with_thumb: number }>();
  const sender = { me: 0, them: 0 };
  const seenAttachments = new Set<number>();
  const seenCategoryAttachments = new Set<string>();

  for (const row of rows) {
    if (!seenAttachments.has(row.id)) {
      seenAttachments.add(row.id);
      if (row.is_from_me === 1) sender.me += 1;
      else sender.them += 1;

      const mimeLabel = cleanAttachmentLabel(row.mime_type, "unknown mime");
      const mime = mimes.get(mimeLabel) ?? {
        label: mimeLabel,
        n: 0,
        total_bytes: 0,
        me: 0,
        them: 0,
        with_thumb: 0,
        images: 0,
        videos: 0,
      };
      mime.n += 1;
      mime.total_bytes += row.total_bytes ?? 0;
      if (row.is_from_me === 1) mime.me += 1;
      else mime.them += 1;
      if (row.thumb_path) mime.with_thumb += 1;
      if (row.is_image === 1) mime.images += 1;
      if (row.is_video === 1) mime.videos += 1;
      mimes.set(mimeLabel, mime);

      const ym = bucket(row.ts, "ym");
      const month = months.get(ym) ?? { ym, n: 0, images: 0, videos: 0, with_thumb: 0 };
      month.n += 1;
      if (row.is_image === 1) month.images += 1;
      if (row.is_video === 1) month.videos += 1;
      if (row.thumb_path) month.with_thumb += 1;
      months.set(ym, month);
    }

    if (row.is_image === 1) {
      const categoryLabel = cleanAttachmentLabel(row.category, row.category_status ?? "unclassified");
      const categoryKey = `${row.id}:${categoryLabel}`;
      if (seenCategoryAttachments.has(categoryKey)) continue;
      seenCategoryAttachments.add(categoryKey);
      const category = categories.get(categoryLabel) ?? { label: categoryLabel, n: 0, with_thumb: 0 };
      category.n += 1;
      if (row.thumb_path) category.with_thumb += 1;
      categories.set(categoryLabel, category);
    }
  }

  return {
    categories: [...categories.values()].sort((a, b) => b.n - a.n || a.label.localeCompare(b.label)).slice(0, 10),
    mime_types: [...mimes.values()].sort((a, b) => b.n - a.n || a.label.localeCompare(b.label)).slice(0, 10),
    top_months: [...months.values()].sort((a, b) => b.n - a.n || b.ym.localeCompare(a.ym)).slice(0, 8),
    sender,
  };
}

function cleanAttachmentLabel(value: string | null, fallback: string) {
  const cleaned = value?.trim();
  return cleaned ? cleaned.replaceAll("_", " ") : fallback.replaceAll("_", " ");
}

function parseSimilarIds(value: unknown): number[] {
  if (typeof value !== "string" || !value) return [];
  try {
    const parsed = JSON.parse(value) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed
      .map((id) => Number(id))
      .filter((id) => Number.isInteger(id) && id > 0);
  } catch {
    return [];
  }
}

// ----- daily for sparkline / drill -----
export const getDaily = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.extend({ ym: z.string().regex(/^\d{4}-\d{2}$/) }).parse(d))
  .handler(async ({ data }) => {
    const bounds = monthBounds(data.ym);
    const scope = messageScopeWhere(resolveMessageScope(data), "m", ["m.ts >= ?", "m.ts < ?"]);
    const rows = db().prepare(`
      SELECT m.ts, m.is_from_me
      FROM messages m
      ${scope.sql}
      ORDER BY m.ts
    `).all(bounds.start, bounds.end, ...scope.args) as Array<{ ts: number; is_from_me: number }>;
    const byDay = new Map<string, { ymd: string; me: number; them: number; total: number }>();
    for (const row of rows) {
      const ymd = bucket(row.ts, "ymd");
      const day = byDay.get(ymd) ?? { ymd, me: 0, them: 0, total: 0 };
      day.total += 1;
      if (row.is_from_me === 1) day.me += 1;
      else day.them += 1;
      byDay.set(ymd, day);
    }
    return [...byDay.values()].sort((a, b) => a.ymd.localeCompare(b.ymd));
  });

// ----- top words -----
//
// Exported so divergence analysis (getWordDivergence) shares the same vocabulary surface
// as the simple per-side top-N (getWordTops).
export const WORD_STOP = STOPWORDS;
export const getWordTops = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }) => {
    const resolved = resolveMessageScope(data);
    return withDbCache(homeScopeCacheKey("word-tops", resolved), () => {
    const scope = messageScopeWhere(resolved, "m", ["m.text IS NOT NULL", "m.text != ''"]);
    const rows = db()
      .prepare(`SELECT m.is_from_me, m.text FROM messages m ${scope.sql}`)
      .iterate(...scope.args) as IterableIterator<{ is_from_me: number; text: string }>;
    const counts: [Map<string, number>, Map<string, number>] = [new Map(), new Map()];
    for (const r of rows) {
      for (const w of tokenize(r.text, { minLen: 3, maxLen: 20 })) {
        if (WORD_STOP.has(w)) continue;
        const c = counts[r.is_from_me];
        c.set(w, (c.get(w) ?? 0) + 1);
      }
    }
    const top = (m: Map<string, number>) => [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, 25).map(([word, n]) => ({ word, n }));
    return { me: top(counts[1]), them: top(counts[0]) };
    });
  });

// ----- word-usage divergence (Monroe, Colaresi & Quinn 2008) -----
//
// "Fightin' Words: Lexical Feature Selection and Evaluation for Identifying the Content
// of Political Conflict." Implements log-odds ratio with informative Dirichlet prior, z-scored.
//
// Per word w in corpus i with combined count y_w over both corpora (size N total tokens):
//   α_w = α₀ · (y_w / N)        (informative prior pulled from combined frequencies)
//   log_odds_i(w) = log( (y_iw + α_w) / (n_i + α₀ - y_iw - α_w) )
//   δ(w)          = log_odds_me(w) - log_odds_them(w)
//   σ²(w)        ≈ 1/(y_me,w + α_w) + 1/(y_them,w + α_w)
//   z(w)          = δ(w) / sqrt(σ²(w))
//
// |z| > 1.96 ≈ 95% significance. Positive z = Me-distinctive, negative = Them.
// α₀ = 100 (moderate informative prior); combined-count floor = 10 to de-noise rare words.
//
// Each row is also annotated with English-baseline lift via wordfreq (see top of file):
//   lift_me / lift_them = (per-token rate in our corpus) / (per-token rate in baseline English)
//   iconic_score        = log10(min(lift_me, lift_them))
//                       — high when BOTH of us use the word much more than average English speakers
//   baseline_zipf       = wordfreq Zipf score, 0 if not in baseline list
// "Iconic to us" = high iconic_score AND |z| small. See `getIconicWords` below.
export type WordDivergence = {
  word: string;
  count_me: number;
  count_them: number;
  log_odds_z: number;
  combined_count: number;
  lift_me: number;
  lift_them: number;
  iconic_score: number;
  baseline_zipf: number;
};

export const getWordDivergence = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => messageScopeInput.parse(d ?? {}))
  .handler(async ({ data }): Promise<WordDivergence[]> => {
    const resolved = resolveMessageScope({ ...data, sender: "both" });
    return withDbCache(homeScopeCacheKey("word-divergence", resolved), () => {
    const scope = messageScopeWhere(
      resolved,
      "m",
      ["m.text IS NOT NULL", "m.text != ''"],
    );
    const rows = db()
      .prepare(`SELECT m.is_from_me, m.text FROM messages m ${scope.sql}`)
      .iterate(...scope.args) as IterableIterator<{ is_from_me: number; text: string }>;

    // counts[0] = them (Them), counts[1] = me (Me) — matches is_from_me indexing.
    const counts: [Map<string, number>, Map<string, number>] = [new Map(), new Map()];
    let nMe = 0;
    let nThem = 0;

    for (const r of rows) {
      for (const w of tokenize(r.text, { minLen: 3, maxLen: 20 })) {
        if (WORD_STOP.has(w)) continue;
        const c = counts[r.is_from_me];
        c.set(w, (c.get(w) ?? 0) + 1);
        if (r.is_from_me === 1) nMe++;
        else nThem++;
      }
    }
    if (nMe === 0 || nThem === 0) return [];

    const N = nMe + nThem;
    const ALPHA0 = 100;
    const MIN_COMBINED = 10;

    // Union of vocabularies, restricted to combined ≥ MIN_COMBINED.
    const vocab = new Set<string>();
    for (const w of counts[0].keys()) vocab.add(w);
    for (const w of counts[1].keys()) vocab.add(w);

    const out: WordDivergence[] = [];
    for (const w of vocab) {
      const yMe = counts[1].get(w) ?? 0;
      const yThem = counts[0].get(w) ?? 0;
      const yW = yMe + yThem;
      if (yW < MIN_COMBINED) continue;

      const alphaW = ALPHA0 * (yW / N);

      // log-odds per side
      const logOddsMe = Math.log((yMe + alphaW) / (nMe + ALPHA0 - yMe - alphaW));
      const logOddsThem = Math.log((yThem + alphaW) / (nThem + ALPHA0 - yThem - alphaW));
      const delta = logOddsMe - logOddsThem;

      // approximate variance from Monroe et al. eq. 22
      const variance = 1 / (yMe + alphaW) + 1 / (yThem + alphaW);
      const z = delta / Math.sqrt(variance);

      // English-baseline lift. Per-token rate in each corpus / per-token rate in baseline.
      // A word with corpus_rate=1e-4 and baseline_rate=1e-6 ⇒ lift = 100× ⇒ log10 = 2.
      const baselineZipf = baselineZipfFor(w);
      const baselineRate = zipfToRate(baselineZipf);
      const corpusRateMe = nMe > 0 ? yMe / nMe : 0;
      const corpusRateThem = nThem > 0 ? yThem / nThem : 0;
      const liftMe = corpusRateMe / baselineRate;
      const liftThem = corpusRateThem / baselineRate;
      // Bottom-bounded: high only when BOTH sides outpace baseline. min() prevents
      // a word that one of us spams from dominating the "shared-iconic" axis.
      const minLift = Math.min(liftMe, liftThem);
      const iconicScore = minLift > 0 ? Math.log10(minLift) : -Infinity;

      out.push({
        word: w,
        count_me: yMe,
        count_them: yThem,
        log_odds_z: z,
        combined_count: yW,
        lift_me: liftMe,
        lift_them: liftThem,
        iconic_score: iconicScore,
        baseline_zipf: baselineZipf,
      });
    }

    // Capped payload: union three axes so the client can rank by any of them without
    // server fetching the full long tail. Keep the top 1000 by |z|, top 200 by combined
    // count, and top 300 by iconic_score so the new "iconic to us" column has options.
    const byAbsZ = [...out].sort((a, b) => Math.abs(b.log_odds_z) - Math.abs(a.log_odds_z)).slice(0, 1000);
    const byFreq = [...out].sort((a, b) => b.combined_count - a.combined_count).slice(0, 200);
    const byIconic = [...out].sort((a, b) => b.iconic_score - a.iconic_score).slice(0, 300);
    const seen = new Set<string>();
    const merged: WordDivergence[] = [];
    for (const w of [...byAbsZ, ...byFreq, ...byIconic]) {
      if (seen.has(w.word)) continue;
      seen.add(w.word);
      merged.push(w);
    }
    // Sort the merged set by |z| descending so the scatter retains the same ordering contract.
    merged.sort((a, b) => Math.abs(b.log_odds_z) - Math.abs(a.log_odds_z));
    return merged;
    });
  });

// ----- iconic-to-us words (English-baseline lift, both sides agree) -----
//
// Returns words that BOTH of us use far more often than average English speakers
// AND that we use at similar rates. Tunable: maxAbsZ caps the asymmetry, minIconicScore
// is a floor on log10(min_lift) (1.0 = ≥10× baseline).
const iconicInput = messageScopeInput.extend({
  minIconicScore: z.number().default(1.0),
  maxAbsZ: z.number().default(1.5),
  limit: z.number().int().min(1).max(500).default(200),
});

export type IconicWord = WordDivergence;

export const getIconicWords = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => iconicInput.parse(d ?? {}))
  .handler(async ({ data }): Promise<IconicWord[]> => {
    const resolved = resolveMessageScope({ ...data, sender: "both" });
    const cacheKey = `${homeScopeCacheKey("iconic-words", resolved)}|min=${data.minIconicScore}|maxAbsZ=${data.maxAbsZ}|limit=${data.limit}`;
    return withDbCache(cacheKey, () => {
    const scope = messageScopeWhere(
      resolved,
      "m",
      ["m.text IS NOT NULL", "m.text != ''"],
    );
    const rows = db()
      .prepare(`SELECT m.is_from_me, m.text FROM messages m ${scope.sql}`)
      .iterate(...scope.args) as IterableIterator<{ is_from_me: number; text: string }>;

    const counts: [Map<string, number>, Map<string, number>] = [new Map(), new Map()];
    let nMe = 0;
    let nThem = 0;

    for (const r of rows) {
      for (const w of tokenize(r.text, { minLen: 3, maxLen: 20 })) {
        if (WORD_STOP.has(w)) continue;
        const c = counts[r.is_from_me];
        c.set(w, (c.get(w) ?? 0) + 1);
        if (r.is_from_me === 1) nMe++;
        else nThem++;
      }
    }
    if (nMe === 0 || nThem === 0) return [];

    const N = nMe + nThem;
    const ALPHA0 = 100;
    const MIN_COMBINED = 10;

    const vocab = new Set<string>();
    for (const w of counts[0].keys()) vocab.add(w);
    for (const w of counts[1].keys()) vocab.add(w);

    const out: IconicWord[] = [];
    for (const w of vocab) {
      const yMe = counts[1].get(w) ?? 0;
      const yThem = counts[0].get(w) ?? 0;
      const yW = yMe + yThem;
      if (yW < MIN_COMBINED) continue;
      // Both sides must use the word at all — otherwise it's distinctive, not shared.
      if (yMe === 0 || yThem === 0) continue;

      const alphaW = ALPHA0 * (yW / N);
      const logOddsMe = Math.log((yMe + alphaW) / (nMe + ALPHA0 - yMe - alphaW));
      const logOddsThem = Math.log((yThem + alphaW) / (nThem + ALPHA0 - yThem - alphaW));
      const delta = logOddsMe - logOddsThem;
      const variance = 1 / (yMe + alphaW) + 1 / (yThem + alphaW);
      const z = delta / Math.sqrt(variance);

      const baselineZipf = baselineZipfFor(w);
      const baselineRate = zipfToRate(baselineZipf);
      const liftMe = (yMe / nMe) / baselineRate;
      const liftThem = (yThem / nThem) / baselineRate;
      const minLift = Math.min(liftMe, liftThem);
      const iconicScore = minLift > 0 ? Math.log10(minLift) : -Infinity;

      if (Math.abs(z) > data.maxAbsZ) continue;
      if (iconicScore < data.minIconicScore) continue;

      out.push({
        word: w,
        count_me: yMe,
        count_them: yThem,
        log_odds_z: z,
        combined_count: yW,
        lift_me: liftMe,
        lift_them: liftThem,
        iconic_score: iconicScore,
        baseline_zipf: baselineZipf,
      });
    }

    out.sort((a, b) => b.iconic_score - a.iconic_score);
    return out.slice(0, data.limit);
    });
  });
