/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TurningPointsRouteImport } from './routes/turning-points'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as RhythmsRouteImport } from './routes/rhythms'
import { Route as ResonanceRouteImport } from './routes/resonance'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as RecurrenceRouteImport } from './routes/recurrence'
import { Route as PhrasesRouteImport } from './routes/phrases'
import { Route as OutliersRouteImport } from './routes/outliers'
import { Route as OpenLoopsRouteImport } from './routes/open-loops'
import { Route as OmensRouteImport } from './routes/omens'
import { Route as MirrorsRouteImport } from './routes/mirrors'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as LifecyclesRouteImport } from './routes/lifecycles'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InformationRouteImport } from './routes/information'
import { Route as IgnitionRouteImport } from './routes/ignition'
import { Route as GravityRouteImport } from './routes/gravity'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as EntrainmentRouteImport } from './routes/entrainment'
import { Route as EchoesRouteImport } from './routes/echoes'
import { Route as DynamicsRouteImport } from './routes/dynamics'
import { Route as DesireSessionsRouteImport } from './routes/desire-sessions'
import { Route as DesirePatternsRouteImport } from './routes/desire-patterns'
import { Route as DesireEvolutionRouteImport } from './routes/desire-evolution'
import { Route as DesireRouteImport } from './routes/desire'
import { Route as CounterfactualsRouteImport } from './routes/counterfactuals'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ConstellationsRouteImport } from './routes/constellations'
import { Route as ComparisonsRouteImport } from './routes/comparisons'
import { Route as ChoreographyRouteImport } from './routes/choreography'
import { Route as CapsulesRouteImport } from './routes/capsules'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttractorsRouteImport } from './routes/attractors'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ArcsRouteImport } from './routes/arcs'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TurningPointsRoute = TurningPointsRouteImport.update({
  id: '/turning-points',
  path: '/turning-points',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmsRoute = RhythmsRouteImport.update({
  id: '/rhythms',
  path: '/rhythms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResonanceRoute = ResonanceRouteImport.update({
  id: '/resonance',
  path: '/resonance',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrenceRoute = RecurrenceRouteImport.update({
  id: '/recurrence',
  path: '/recurrence',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasesRoute = PhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const OutliersRoute = OutliersRouteImport.update({
  id: '/outliers',
  path: '/outliers',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenLoopsRoute = OpenLoopsRouteImport.update({
  id: '/open-loops',
  path: '/open-loops',
  getParentRoute: () => rootRouteImport,
} as any)
const OmensRoute = OmensRouteImport.update({
  id: '/omens',
  path: '/omens',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorsRoute = MirrorsRouteImport.update({
  id: '/mirrors',
  path: '/mirrors',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecyclesRoute = LifecyclesRouteImport.update({
  id: '/lifecycles',
  path: '/lifecycles',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const IgnitionRoute = IgnitionRouteImport.update({
  id: '/ignition',
  path: '/ignition',
  getParentRoute: () => rootRouteImport,
} as any)
const GravityRoute = GravityRouteImport.update({
  id: '/gravity',
  path: '/gravity',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrainmentRoute = EntrainmentRouteImport.update({
  id: '/entrainment',
  path: '/entrainment',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoesRoute = EchoesRouteImport.update({
  id: '/echoes',
  path: '/echoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicsRoute = DynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => rootRouteImport,
} as any)
const DesireSessionsRoute = DesireSessionsRouteImport.update({
  id: '/desire-sessions',
  path: '/desire-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DesirePatternsRoute = DesirePatternsRouteImport.update({
  id: '/desire-patterns',
  path: '/desire-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const DesireEvolutionRoute = DesireEvolutionRouteImport.update({
  id: '/desire-evolution',
  path: '/desire-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const DesireRoute = DesireRouteImport.update({
  id: '/desire',
  path: '/desire',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterfactualsRoute = CounterfactualsRouteImport.update({
  id: '/counterfactuals',
  path: '/counterfactuals',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationsRoute = ConstellationsRouteImport.update({
  id: '/constellations',
  path: '/constellations',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsRoute = ComparisonsRouteImport.update({
  id: '/comparisons',
  path: '/comparisons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoreographyRoute = ChoreographyRouteImport.update({
  id: '/choreography',
  path: '/choreography',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesRoute = CapsulesRouteImport.update({
  id: '/capsules',
  path: '/capsules',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractorsRoute = AttractorsRouteImport.update({
  id: '/attractors',
  path: '/attractors',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsRoute = ArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/attachments': typeof AttachmentsRoute
  '/attractors': typeof AttractorsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/browse': typeof BrowseRoute
  '/capsules': typeof CapsulesRoute
  '/choreography': typeof ChoreographyRoute
  '/comparisons': typeof ComparisonsRoute
  '/constellations': typeof ConstellationsRoute
  '/conversations': typeof ConversationsRoute
  '/counterfactuals': typeof CounterfactualsRoute
  '/desire': typeof DesireRoute
  '/desire-evolution': typeof DesireEvolutionRoute
  '/desire-patterns': typeof DesirePatternsRoute
  '/desire-sessions': typeof DesireSessionsRoute
  '/dynamics': typeof DynamicsRoute
  '/echoes': typeof EchoesRoute
  '/entrainment': typeof EntrainmentRoute
  '/forecasts': typeof ForecastsRoute
  '/gestures': typeof GesturesRoute
  '/gravity': typeof GravityRoute
  '/ignition': typeof IgnitionRoute
  '/information': typeof InformationRoute
  '/insights': typeof InsightsRoute
  '/lifecycles': typeof LifecyclesRoute
  '/methods': typeof MethodsRoute
  '/mirrors': typeof MirrorsRoute
  '/omens': typeof OmensRoute
  '/open-loops': typeof OpenLoopsRoute
  '/outliers': typeof OutliersRoute
  '/phrases': typeof PhrasesRoute
  '/recurrence': typeof RecurrenceRoute
  '/repair': typeof RepairRoute
  '/resonance': typeof ResonanceRoute
  '/rhythms': typeof RhythmsRoute
  '/rituals': typeof RitualsRoute
  '/seasons': typeof SeasonsRoute
  '/timeline': typeof TimelineRoute
  '/turning-points': typeof TurningPointsRoute
  '/vocabulary': typeof VocabularyRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/attachments': typeof AttachmentsRoute
  '/attractors': typeof AttractorsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/browse': typeof BrowseRoute
  '/capsules': typeof CapsulesRoute
  '/choreography': typeof ChoreographyRoute
  '/comparisons': typeof ComparisonsRoute
  '/constellations': typeof ConstellationsRoute
  '/conversations': typeof ConversationsRoute
  '/counterfactuals': typeof CounterfactualsRoute
  '/desire': typeof DesireRoute
  '/desire-evolution': typeof DesireEvolutionRoute
  '/desire-patterns': typeof DesirePatternsRoute
  '/desire-sessions': typeof DesireSessionsRoute
  '/dynamics': typeof DynamicsRoute
  '/echoes': typeof EchoesRoute
  '/entrainment': typeof EntrainmentRoute
  '/forecasts': typeof ForecastsRoute
  '/gestures': typeof GesturesRoute
  '/gravity': typeof GravityRoute
  '/ignition': typeof IgnitionRoute
  '/information': typeof InformationRoute
  '/insights': typeof InsightsRoute
  '/lifecycles': typeof LifecyclesRoute
  '/methods': typeof MethodsRoute
  '/mirrors': typeof MirrorsRoute
  '/omens': typeof OmensRoute
  '/open-loops': typeof OpenLoopsRoute
  '/outliers': typeof OutliersRoute
  '/phrases': typeof PhrasesRoute
  '/recurrence': typeof RecurrenceRoute
  '/repair': typeof RepairRoute
  '/resonance': typeof ResonanceRoute
  '/rhythms': typeof RhythmsRoute
  '/rituals': typeof RitualsRoute
  '/seasons': typeof SeasonsRoute
  '/timeline': typeof TimelineRoute
  '/turning-points': typeof TurningPointsRoute
  '/vocabulary': typeof VocabularyRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/attachments': typeof AttachmentsRoute
  '/attractors': typeof AttractorsRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/browse': typeof BrowseRoute
  '/capsules': typeof CapsulesRoute
  '/choreography': typeof ChoreographyRoute
  '/comparisons': typeof ComparisonsRoute
  '/constellations': typeof ConstellationsRoute
  '/conversations': typeof ConversationsRoute
  '/counterfactuals': typeof CounterfactualsRoute
  '/desire': typeof DesireRoute
  '/desire-evolution': typeof DesireEvolutionRoute
  '/desire-patterns': typeof DesirePatternsRoute
  '/desire-sessions': typeof DesireSessionsRoute
  '/dynamics': typeof DynamicsRoute
  '/echoes': typeof EchoesRoute
  '/entrainment': typeof EntrainmentRoute
  '/forecasts': typeof ForecastsRoute
  '/gestures': typeof GesturesRoute
  '/gravity': typeof GravityRoute
  '/ignition': typeof IgnitionRoute
  '/information': typeof InformationRoute
  '/insights': typeof InsightsRoute
  '/lifecycles': typeof LifecyclesRoute
  '/methods': typeof MethodsRoute
  '/mirrors': typeof MirrorsRoute
  '/omens': typeof OmensRoute
  '/open-loops': typeof OpenLoopsRoute
  '/outliers': typeof OutliersRoute
  '/phrases': typeof PhrasesRoute
  '/recurrence': typeof RecurrenceRoute
  '/repair': typeof RepairRoute
  '/resonance': typeof ResonanceRoute
  '/rhythms': typeof RhythmsRoute
  '/rituals': typeof RitualsRoute
  '/seasons': typeof SeasonsRoute
  '/timeline': typeof TimelineRoute
  '/turning-points': typeof TurningPointsRoute
  '/vocabulary': typeof VocabularyRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcs'
    | '/ask'
    | '/atlas'
    | '/attachments'
    | '/attractors'
    | '/auth'
    | '/bids'
    | '/browse'
    | '/capsules'
    | '/choreography'
    | '/comparisons'
    | '/constellations'
    | '/conversations'
    | '/counterfactuals'
    | '/desire'
    | '/desire-evolution'
    | '/desire-patterns'
    | '/desire-sessions'
    | '/dynamics'
    | '/echoes'
    | '/entrainment'
    | '/forecasts'
    | '/gestures'
    | '/gravity'
    | '/ignition'
    | '/information'
    | '/insights'
    | '/lifecycles'
    | '/methods'
    | '/mirrors'
    | '/omens'
    | '/open-loops'
    | '/outliers'
    | '/phrases'
    | '/recurrence'
    | '/repair'
    | '/resonance'
    | '/rhythms'
    | '/rituals'
    | '/seasons'
    | '/timeline'
    | '/turning-points'
    | '/vocabulary'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcs'
    | '/ask'
    | '/atlas'
    | '/attachments'
    | '/attractors'
    | '/auth'
    | '/bids'
    | '/browse'
    | '/capsules'
    | '/choreography'
    | '/comparisons'
    | '/constellations'
    | '/conversations'
    | '/counterfactuals'
    | '/desire'
    | '/desire-evolution'
    | '/desire-patterns'
    | '/desire-sessions'
    | '/dynamics'
    | '/echoes'
    | '/entrainment'
    | '/forecasts'
    | '/gestures'
    | '/gravity'
    | '/ignition'
    | '/information'
    | '/insights'
    | '/lifecycles'
    | '/methods'
    | '/mirrors'
    | '/omens'
    | '/open-loops'
    | '/outliers'
    | '/phrases'
    | '/recurrence'
    | '/repair'
    | '/resonance'
    | '/rhythms'
    | '/rituals'
    | '/seasons'
    | '/timeline'
    | '/turning-points'
    | '/vocabulary'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/arcs'
    | '/ask'
    | '/atlas'
    | '/attachments'
    | '/attractors'
    | '/auth'
    | '/bids'
    | '/browse'
    | '/capsules'
    | '/choreography'
    | '/comparisons'
    | '/constellations'
    | '/conversations'
    | '/counterfactuals'
    | '/desire'
    | '/desire-evolution'
    | '/desire-patterns'
    | '/desire-sessions'
    | '/dynamics'
    | '/echoes'
    | '/entrainment'
    | '/forecasts'
    | '/gestures'
    | '/gravity'
    | '/ignition'
    | '/information'
    | '/insights'
    | '/lifecycles'
    | '/methods'
    | '/mirrors'
    | '/omens'
    | '/open-loops'
    | '/outliers'
    | '/phrases'
    | '/recurrence'
    | '/repair'
    | '/resonance'
    | '/rhythms'
    | '/rituals'
    | '/seasons'
    | '/timeline'
    | '/turning-points'
    | '/vocabulary'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcsRoute: typeof ArcsRoute
  AskRoute: typeof AskRoute
  AtlasRoute: typeof AtlasRoute
  AttachmentsRoute: typeof AttachmentsRoute
  AttractorsRoute: typeof AttractorsRoute
  AuthRoute: typeof AuthRoute
  BidsRoute: typeof BidsRoute
  BrowseRoute: typeof BrowseRoute
  CapsulesRoute: typeof CapsulesRoute
  ChoreographyRoute: typeof ChoreographyRoute
  ComparisonsRoute: typeof ComparisonsRoute
  ConstellationsRoute: typeof ConstellationsRoute
  ConversationsRoute: typeof ConversationsRoute
  CounterfactualsRoute: typeof CounterfactualsRoute
  DesireRoute: typeof DesireRoute
  DesireEvolutionRoute: typeof DesireEvolutionRoute
  DesirePatternsRoute: typeof DesirePatternsRoute
  DesireSessionsRoute: typeof DesireSessionsRoute
  DynamicsRoute: typeof DynamicsRoute
  EchoesRoute: typeof EchoesRoute
  EntrainmentRoute: typeof EntrainmentRoute
  ForecastsRoute: typeof ForecastsRoute
  GesturesRoute: typeof GesturesRoute
  GravityRoute: typeof GravityRoute
  IgnitionRoute: typeof IgnitionRoute
  InformationRoute: typeof InformationRoute
  InsightsRoute: typeof InsightsRoute
  LifecyclesRoute: typeof LifecyclesRoute
  MethodsRoute: typeof MethodsRoute
  MirrorsRoute: typeof MirrorsRoute
  OmensRoute: typeof OmensRoute
  OpenLoopsRoute: typeof OpenLoopsRoute
  OutliersRoute: typeof OutliersRoute
  PhrasesRoute: typeof PhrasesRoute
  RecurrenceRoute: typeof RecurrenceRoute
  RepairRoute: typeof RepairRoute
  ResonanceRoute: typeof ResonanceRoute
  RhythmsRoute: typeof RhythmsRoute
  RitualsRoute: typeof RitualsRoute
  SeasonsRoute: typeof SeasonsRoute
  TimelineRoute: typeof TimelineRoute
  TurningPointsRoute: typeof TurningPointsRoute
  VocabularyRoute: typeof VocabularyRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turning-points': {
      id: '/turning-points'
      path: '/turning-points'
      fullPath: '/turning-points'
      preLoaderRoute: typeof TurningPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythms': {
      id: '/rhythms'
      path: '/rhythms'
      fullPath: '/rhythms'
      preLoaderRoute: typeof RhythmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resonance': {
      id: '/resonance'
      path: '/resonance'
      fullPath: '/resonance'
      preLoaderRoute: typeof ResonanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrence': {
      id: '/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof RecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrases': {
      id: '/phrases'
      path: '/phrases'
      fullPath: '/phrases'
      preLoaderRoute: typeof PhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outliers': {
      id: '/outliers'
      path: '/outliers'
      fullPath: '/outliers'
      preLoaderRoute: typeof OutliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-loops': {
      id: '/open-loops'
      path: '/open-loops'
      fullPath: '/open-loops'
      preLoaderRoute: typeof OpenLoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omens': {
      id: '/omens'
      path: '/omens'
      fullPath: '/omens'
      preLoaderRoute: typeof OmensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirrors': {
      id: '/mirrors'
      path: '/mirrors'
      fullPath: '/mirrors'
      preLoaderRoute: typeof MirrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycles': {
      id: '/lifecycles'
      path: '/lifecycles'
      fullPath: '/lifecycles'
      preLoaderRoute: typeof LifecyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ignition': {
      id: '/ignition'
      path: '/ignition'
      fullPath: '/ignition'
      preLoaderRoute: typeof IgnitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravity': {
      id: '/gravity'
      path: '/gravity'
      fullPath: '/gravity'
      preLoaderRoute: typeof GravityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrainment': {
      id: '/entrainment'
      path: '/entrainment'
      fullPath: '/entrainment'
      preLoaderRoute: typeof EntrainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echoes': {
      id: '/echoes'
      path: '/echoes'
      fullPath: '/echoes'
      preLoaderRoute: typeof EchoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamics': {
      id: '/dynamics'
      path: '/dynamics'
      fullPath: '/dynamics'
      preLoaderRoute: typeof DynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desire-sessions': {
      id: '/desire-sessions'
      path: '/desire-sessions'
      fullPath: '/desire-sessions'
      preLoaderRoute: typeof DesireSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desire-patterns': {
      id: '/desire-patterns'
      path: '/desire-patterns'
      fullPath: '/desire-patterns'
      preLoaderRoute: typeof DesirePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desire-evolution': {
      id: '/desire-evolution'
      path: '/desire-evolution'
      fullPath: '/desire-evolution'
      preLoaderRoute: typeof DesireEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desire': {
      id: '/desire'
      path: '/desire'
      fullPath: '/desire'
      preLoaderRoute: typeof DesireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterfactuals': {
      id: '/counterfactuals'
      path: '/counterfactuals'
      fullPath: '/counterfactuals'
      preLoaderRoute: typeof CounterfactualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellations': {
      id: '/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof ConstellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons': {
      id: '/comparisons'
      path: '/comparisons'
      fullPath: '/comparisons'
      preLoaderRoute: typeof ComparisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choreography': {
      id: '/choreography'
      path: '/choreography'
      fullPath: '/choreography'
      preLoaderRoute: typeof ChoreographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules': {
      id: '/capsules'
      path: '/capsules'
      fullPath: '/capsules'
      preLoaderRoute: typeof CapsulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractors': {
      id: '/attractors'
      path: '/attractors'
      fullPath: '/attractors'
      preLoaderRoute: typeof AttractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs': {
      id: '/arcs'
      path: '/arcs'
      fullPath: '/arcs'
      preLoaderRoute: typeof ArcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcsRoute: ArcsRoute,
  AskRoute: AskRoute,
  AtlasRoute: AtlasRoute,
  AttachmentsRoute: AttachmentsRoute,
  AttractorsRoute: AttractorsRoute,
  AuthRoute: AuthRoute,
  BidsRoute: BidsRoute,
  BrowseRoute: BrowseRoute,
  CapsulesRoute: CapsulesRoute,
  ChoreographyRoute: ChoreographyRoute,
  ComparisonsRoute: ComparisonsRoute,
  ConstellationsRoute: ConstellationsRoute,
  ConversationsRoute: ConversationsRoute,
  CounterfactualsRoute: CounterfactualsRoute,
  DesireRoute: DesireRoute,
  DesireEvolutionRoute: DesireEvolutionRoute,
  DesirePatternsRoute: DesirePatternsRoute,
  DesireSessionsRoute: DesireSessionsRoute,
  DynamicsRoute: DynamicsRoute,
  EchoesRoute: EchoesRoute,
  EntrainmentRoute: EntrainmentRoute,
  ForecastsRoute: ForecastsRoute,
  GesturesRoute: GesturesRoute,
  GravityRoute: GravityRoute,
  IgnitionRoute: IgnitionRoute,
  InformationRoute: InformationRoute,
  InsightsRoute: InsightsRoute,
  LifecyclesRoute: LifecyclesRoute,
  MethodsRoute: MethodsRoute,
  MirrorsRoute: MirrorsRoute,
  OmensRoute: OmensRoute,
  OpenLoopsRoute: OpenLoopsRoute,
  OutliersRoute: OutliersRoute,
  PhrasesRoute: PhrasesRoute,
  RecurrenceRoute: RecurrenceRoute,
  RepairRoute: RepairRoute,
  ResonanceRoute: ResonanceRoute,
  RhythmsRoute: RhythmsRoute,
  RitualsRoute: RitualsRoute,
  SeasonsRoute: SeasonsRoute,
  TimelineRoute: TimelineRoute,
  TurningPointsRoute: TurningPointsRoute,
  VocabularyRoute: VocabularyRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
